/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TradingConsole;

import TradingConsole.ui.MainFrame;

public class App {

    public static void main(String[] args) {
        MainFrame mf = new MainFrame();
    }
    
}
